---
title: "GAM Effect Heredity with Spike-and-slab prior"
output: pdf_document
---
\newcommand{\bs}[1]{\boldsymbol{#1}}
\newcommand{\tp}{*}
\newcommand{\pr}{\text{Pr}}

# Prior of Selection Indicator

We assume that the linear and non-linear coefficients $\beta_{j}$ and $\bs \beta_{j\cdot}$ follows the spike and slab lasso prior with selection indicator $\gamma_j$ and $\gamma_j^\tp$ respectively. We further assume both $\gamma_j$ and $\gamma_j^\tp$ follow binomial distribution of trial 1,
\begin{align*}
\gamma_{j} | \theta_j \sim Bin(1, \theta_j)\\
\gamma_{j}^\tp | \theta_j \sim Bin(1, \theta_j^\tp),
\end{align*}
  where $\theta_j^\tp = w_j\theta_j$ and $w_j \in [0,1]$ is a dynamic weight implementing the effect heredity (Chipman, 2004). Depends on the definition of effect heredity , $w_j$ can be a constant (hyperparameter $\pi_4$ for quadratic terms defined in Chipman (2004)), a function of $Pr(\gamma_j=1)$ (implemented in `BhGLM`). If we define effect heredity to be strict, i.e. effect forcing (Chipman, 2004), we can have $w_j = \gamma_j$ such that $\gamma_j^\tp = 1$ enters the model only when $\gamma_j$ enters the model. At last, we assume $\theta_j \sim Beta(1,1)$ for calculation simplicity.

With this formulation, 
