---
title: "Spike-and-Slab Generalized Additive Models and Scalable Algorithms for High-Dimensional Data"

abstract: "There are proposals that extend the classical generalized additive models (GAMs) to accommodate the high-dimensional (p>>n) problem using group penalties and priors. These models rarely smooth the nonlinear effect properly because of the sparse regularization. It leads to excess shrinkage on coefficients and inaccurate prediction. Besides, most of these GAMs consider an “all-in-all-out” approach for function selection, rendering them difficult to answer if nonlinear effects are necessary. While some Bayesian models can address the shortcomings, using Markov chain Monte Carlo (MCMC) algorithms for model fitting creates a new challenge, scalability. Hence, we propose Bayesian hierarchical generalized additive models as a solution. For smooth and sparse solutions, the proposed models employ bi-part spike-and-slab spline priors, including mixture double exponential and mixture normal priors. Two optimization-based algorithms, EM-Coordinate Descent and EM-Iterative Weighted Least Squares, are developed for expedited computation. Simulation studies and metabolomics data analyses demonstrate improved performance against state-of-art models, mgcv, COSSO and sparse Bayesian GAM. The software implementation of the proposed models is freely available via an R package BHAM."
keywords: Spike-and-Slab Priors; High-Dimensional Data; Generalized Additive Models; EM-IWLS; EM-Coordinate Decent
bibliography: bibfile.bib
output: 
  word_document:
    reference_docx: template.docx
header-includes: 
  - \usepackage{tikz}
  - \usepackage{pgfplots}
---

<!-- \usepackage{tikz} -->
\pgfplotsset{compat=1.18}
\usetikzlibrary{shapes.geometric, arrows, positioning, calc, matrix, backgrounds, fit}
\newcommand{\bs}[1]{\boldsymbol{#1}}
\newcommand{\tp}{*}
\newcommand{\repa}{\text{repa}}
\newcommand{\pr}{\text{Pr}}


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(knitr)
library(targets)
# library(here)
library(xtable)

tar_load(intro_path)
tar_load(method_path)
tar_load(sim_path)
tar_load(real_data_path)
tar_load(disc_path)

tar_load(tab_binom)
tar_load(tab_gaus)

tar_load(WLM_train_dat)
# tar_load(tbl_one)
tar_load(ECB_bamlasso_cv)
tar_load(ECB_SBGAM_cv)
tar_load(WLM_bamlasso_cv)
tar_load(WLM_SBGAM_cv)
tar_load(tbl_real_time)
```

\newpage

```{r child="01-Intro.Rmd"}
```

```{r child="02-Method.Rmd"}
```

```{r child="03-Simulation.Rmd"}
```

```{r child="04-Real_Data.Rmd"}
```

```{r child="05-Discussion.Rmd"}
```