---
title: Spike-and-Slab Generalized Additive Models and Scalable Algorithms for High-Dimensional Data
author:
- name: Boyi Guo*
  num: a
- name: Byron C. Jaeger
  num: b 
- name: AKM Fazlur Rahman
  num: a   
- name: D. Leann Long
  num: a  
- name: Nengjun Yi*
  num: a
address:
- num: a
  org: Department of Biostatistics, University of Alabama at Birmingham, Birmingham, USA
- num: b
  org: Department of Biostatistics and Data Science, Wake Forest University, Winston-Salem, USA
corres: "Boyi Guo and Nengjun Yi, Department of Biostatistics, University of Alabama at Birmingham, Birmingham, USA. \\email{boyiguo1@uab.edu},  \\email{nyi@uab.edu}"
presentaddress: This is sample for present address text this is sample for present address text
authormark: Guo et al.
articletype: Research article
received: 2021-01-01
revised: 2021-02-01
accepted: 2021-03-01
abstract: "There are proposals that extend the classical generalized additive models (GAMs) to accommodate the high-dimensional ($p>>n$) problem using group penalties and priors. These models rarely smooth the nonlinear effect properly as the sparse regularization leads to excess shrinkage on coefficients and inaccurate prediction. Moreover, most of these GAMs consider an “all-in-all-out” approach for function selection, rendering them difficult to answer if nonlinear effects are necessary. While some Bayesian models can address these shortcomings, using Markov chain Monte Carlo (MCMC) algorithms for model fitting creates a new challenge, scalability. Hence, we propose Bayesian hierarchical generalized additive models as a solution: we propose a novel spike-and-slab spline prior for smoothing functions, where a reparameterization step facilitates smoothing penalty and separate selection of linear and nonlinear spaces. Two scalable and deterministic algorithms, EM-Coordinate Descent and EM-Iterative Weighted Least Squares, are developed to fit the proposed model. Simulation studies and metabolomics data analyses demonstrate improved performance against state-of-the-art models, mgcv, COSSO and sparse Bayesian GAM. The software implementation of the proposed models is freely available via an R package BHAM."
keywords: Spike-and-Slab Priors; High-Dimensional Data; Generalized Additive Models; EM-IWLS; EM-Coordinate Decent; Scalablility
bibliography: bibfile.bib
output: 
  rticles::sim_article:
    keep_tex: TRUE
header-includes: 
  - \usepackage{tikz}
  - \usepackage{pgfplots}
---

<!-- \usepackage{tikz} -->
\pgfplotsset{compat=1.18}
\usetikzlibrary{shapes.geometric, arrows, positioning, calc, matrix, backgrounds, fit}
\newcommand{\bs}[1]{\boldsymbol{#1}}
\newcommand{\tp}{*}
\newcommand{\pr}{\text{Pr}}
\newcommand{\repa}{\text{repa}}
\newcommand{\simiid}{\overset{\text{iid}}{\sim}}


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(knitr)
library(targets)
# library(here)
library(xtable)
library(flextable)


set_flextable_defaults(fonts_ignore=TRUE)

tar_load(intro_path)
tar_load(method_path)
tar_load(sim_path)
tar_load(real_data_path)
tar_load(disc_path)

tar_load(tab_binom)
tar_load(tab_gaus)

tar_load(WLM_train_dat)
# tar_load(tbl_one)
tar_load(ECB_bamlasso_cv)
tar_load(ECB_SBGAM_cv)
tar_load(WLM_bamlasso_cv)
tar_load(WLM_SBGAM_cv)
tar_load(tbl_real_time)
```

```{r child="01-Intro.Rmd"}
```

```{r child="02-Method.Rmd"}
```

```{r child="03-Simulation.Rmd"}
```

```{r child="04-Real_Data.Rmd"}
```

```{r child="05-Discussion.Rmd"}
```


