---
title: Spike-and-Slab Generalized Additive Models and Scalable Algorithms for High-Dimensional Data

# author: 
# - name: Author 1
  # affiliation: Department of YYY, University of XXX
  # email: abc@def
  
# - name: Author 2
  # affiliation: Department of ZZZ, University of WWW
  # email: djf@wef

keywords: Spike-and-Slab Priors; High-Dimensional Data; Generalized Additive Models; EM-IWLS; EM-Coordinate Decent; Scalablility

abstract: |
  Many proposed high-dimensional generalized additive models (GAMs) use sparse regularization, and tend to overly smooth important nonlinear functions. The excess shrinkage on coefficients can in turn produce inaccurate predictions. Moreover, most of these GAMs consider an “all-in-all-out” approach for function selection, rendering them difficult to answer if nonlinear effects are necessary. While some Bayesian models can address these shortcomings, using Markov chain Monte Carlo algorithms for model fitting creates a new challenge, scalability. Hence, we propose Bayesian hierarchical generalized additive models as a solution: we incorporate the smoothing penalty that can separate linear and nonlinear spaces of smoothing function. A novel spike-and-slab spline prior is used to select the components of smoothing functions. Two scalable and deterministic algorithms, EM-Coordinate Descent and EM-Iterative Weighted Least Squares, are developed for different utilities. Simulation studies and metabolomics data analyses demonstrate improved performance against state-of-the-art models, mgcv, COSSO and sparse Bayesian GAM. The software implementation is freely available via an R package BHAM.

bibliography: bibfile.bib
output: rticles::biometrics_article
# month: "`r format(Sys.Date(), '%b')`"
# year: "`r format(Sys.Date(), '%Y')`"
referee: true # Papers submitted to Biometrics should ALWAYS be prepared
              # using the referee option!!!! Turn off only to preview
              # two column-format
header-includes: 
  - \usepackage{tikz}
  - \usepackage{pgfplots}
  - \usepackage{amsfonts}
  # - \usepackage[modulo,pagewise,displaymath,mathlines]{lineno}
---

<!-- \usepackage{tikz} -->
<!-- \linenumbers -->
\pgfplotsset{compat=1.18}
\usetikzlibrary{shapes.geometric, arrows, positioning, calc, matrix, backgrounds, fit}
\newcommand{\bs}[1]{\boldsymbol{#1}}
\newcommand{\tp}{*}
\newcommand{\pr}{\text{Pr}}
\newcommand{\repa}{\text{repa}}
\newcommand{\simiid}{\overset{\text{iid}}{\sim}}


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(knitr)
library(targets)
# library(here)
library(xtable)
library(flextable)


set_flextable_defaults(fonts_ignore=TRUE)

tar_load(intro_path)
tar_load(method_path)
tar_load(sim_path)
tar_load(real_data_path)
tar_load(disc_path)

tar_load(tab_binom)
tar_load(tab_gaus)

tar_load(WLM_train_dat)
# tar_load(tbl_one)
tar_load(ECB_bamlasso_cv)
tar_load(ECB_SBGAM_cv)
tar_load(WLM_bamlasso_cv)
tar_load(WLM_SBGAM_cv)
tar_load(tbl_real_time)
```

```{r child="01-Intro.Rmd"}
```
```{r child="02-Method.Rmd"}
```

```{r child="03-Simulation.Rmd"}
```

```{r child="04-Real_Data.Rmd"}
```

```{r child="05-Discussion.Rmd"}
```