# Metabolomics Data Analysis
\label{sec:real_data}

In this section, we apply the proposed models BHAM-SSL, fitted with the EM-CD algorithm, to analyze two real-world metabolomics datasets where the outcomes are binary and continuous respectively. We demonstrate the improved prediction performance compared to the other Bayesian hierarchical additive model, SB-GAM [@Bai2021]. Computation time for cross-validation and optimal model fitting steps are recorded and presented in Table \ref{tab:time_real_data}.
\begin{center}
Table \ref{tab:time_real_data} here
\end{center}

## Emory Cardiovascular Biobank
We use the proposed models BHAM-SSL to analyze a metabolic dataset from a recently published research [@Mehta2020] studying plasma metabolomic profile on the three-year all-cause mortality among patients undergoing cardiac catheterization. The dataset is publicly available via \textit{Dryad} [@Mehta2020_data]. It contains in total of 776 subjects from two cohorts. As there is a large number of non-overlapping features among the two cohorts, we use the cohort with larger sample size (N=454). There were initially 6796 features in the dataset, which is too large to be practically meaningful to analyze. Hence, we performed a univariate screening procedure on the features, via GAM implemented in \texttt{mgcv}, and chose the the top 200 features with smallest p-values. We used 5-knot spline additive models for binary outcome using two different models, the proposed BHAM-SSL and the SB-GAM. 10-Fold cross-validation(CV) are used to choose the optimal tuning parameters of each framework with respect to the default selection criterion implemented in the software. Out-of-bag samples were used for prediction performance evaluation, where deviance, AUC, Brier score defined as $\frac{1}{n}\sum\limits^{n}_{i=1}(y_i - \hat y_i)^2$, and misclassication error defined as $\frac{1}{n}\sum\limits^{n}_{i=1}I(|y_i - \hat y_i|>0.5)$ were calculated. BHAM-CD obtained superior AUC, Brier score, and misclassification error in the out-of-bag samples compared to SB-GAM (Table \ref{tab:ECB_res}).
\begin{center}
Table \ref{tab:ECB_res} here
\end{center}

## Weight Loss Maintenance Cohort 
We use the proposed models BHAM-SSL to analyze metabolomics data from a recently published study [@Bihlmeyer2021] on the association between metabolic biomarkers and weight loss, where the dataset is publicly available [@Bihlmeyer2021_data]. In this analysis, we primarily focused on the analysis of one of the three studies included, weight loss maintenance (WLM) cohort [@Svetkey2008], due to the drastically different intervention effects. In the dataset, 765 metaboliltes in baseline plasma collected were profiled using liquid chromatography mass spectrometry. Quality control and natural log transformation were performed during metabolites data preparation. The outcome of interest was standardized percent change in insulin resistance, and hence modeled using a Gaussian model. After removing missing datapoints and addressing outliers in the data, there were $p$=`r nrow(WLM_train_dat)` features remaining in the analysis. 5-Knot spline additive models for the gaussian outcome are constructed using two different models, the proposed BHAM-SSL and the SB-GAM. 10-Fold cross-validation(CV) are used to choose the optimal tuning parameters of each framework with respect to the default selection criterion implemented in the software. Out-of-bag samples were used for prediction performance evaluation, where deviance, $R^2$, mean squared error (MSE) defined as $\frac{1}{n}\sum\limits^{n}_{i=1}(y_i - \hat y_i)^2$, and mean absolute error (MAE) defined as $\frac{1}{n}\sum\limits^{n}_{i=1}|y_i - \hat y_i|$ were calculated. BHAM-CD obtained superior R2, MSE, and MAE in the out-of-bag samples compared to SB-GAM (Table \ref{tab:WLM_res}).
\begin{center}
Table \ref{tab:WLM_res} here
\end{center}
