# Discussion
In the paper, we described a novel generalized additive model using Bayesian hierarchical priors, particularly the proposed spike-and-slab spline prior for bi-level functional selection. Meanwhile, we introduced two optimization based algorithms for model fitting. The algorithms can be easily scale up to address high-dimensional data analysis in a computational efficient manner, but also provide naive inferential supports for many commonly used hierarchical priors, e.g. t-distribution, double exponential distribution, mixture t distribution, and mixture double exponential distribution, in the analyses that the sparse assumption is weak or not necessary. Via simulations, we demonstrated that the proposed model provides as good, if not better, prediction performance compared to some state-of-the-art non-linear modeling devices. 

The proposed model shares many commonality with an high-dimensional Bayesian GAM, SB-GAM [@Bai2021], independently developed around the same time of this work. Both frameworks emphasize computational efficiency by deploying group spike-and-slab lasso type of priors and optimization-based fast and scalable algorithms. Bai provided the theoretical proof for the consistency of variable selection using group spike-and-slab lasso prior. Nevertheless, SB-GAM fails to address the bi-level functional selection and the model inference. The proposed model provides solutions to these remaining questions while maintaining the same level of prediction accuracy. Moreover, the proposed model renders additional flexibility to model specification, allowing various choices of smoothing functions and degrees of freedom.

For transnational science purpose, we implemented the proposed model in a R package \texttt{BHAM}, deposited at [https://github.com/boyiguo1/BHAM](https://github.com/boyiguo1/BHAM). To maximize the flexibility of smoothing function specification, we deploy the same programming grammar as in the state-of-the-art package \texttt{mgcv}, in contrast to previous tools where smoothing functions are limited to the default ones. Ancillary functions are provided for model specification in high-dimensional settings, curve plotting and functional selection.

<!-- the implementation of ssGAM-NM using EM-IRLS. Nevertheless, EM-IRLS are not limited to fitting ssGAM-NM. Other spike-and-slab prior can be fitted with EM-IRLS as well, e.g. mixture t-distribution, and mixture double exponential distributions. @Yi2012 demonstrated that t prior and double exponential prior can be seen hierarchical normal priors, -->
<!-- $$ -->
<!-- \begin{aligned} -->
<!-- \beta_i \sim N(0, \tau^2_i),\\ -->
<!-- \tau^2_i \sim Inv-\chi^2(v, s^2_j) \text{ or } \tau^2_i \sim Gamma(1, s^2/2) -->
<!-- \end{aligned} -->
<!-- $$ -->
<!-- with $\tau^2$ integrated out analytically. Hence, the EM-IRLS can be easily applied to those two additional mixture priors. One of the advantage of using mixture $t$ prior over mixture normal prior is that $t$ distributions with low degree of freedom, e.g. $v=1$, have heavier tail than the normal distribution, which is also a special case of $t$ distribution when $v=\infty$. The heavier tails help to obtain posteriors that concentrated around the true nonzero coefficients at optimal rates. [@Rockova2014a] -->

There are some improvements possible for the proposed models. First of all, the proposed model achieves a bi-level selection via the two-part spike-and-slab spline prior. Nevertheless, this set-up could result in a situation that is not theoretically sound: the non-linear component is selected, but the linear component is not. We currently address it analytically by forcing to include the linear component when non-linear component is included. Another possible solution is to impose an dependent structure of $\gamma_{j}^{pen}$ on $\gamma_{j^{0}}$, i.e. $\gamma_j^{pen}|\gamma_{j}^{0}, \theta_j$. Secondly, while the proposed model addresses a great deal of analytic problem, analyzing the time-to-event outcome remains unsolved. Our current effort resides on expanding GAM to Cox proportional hazard models. An naive approach would be convert an time-to-event outcome to a poisson outcome following Whitehead [@Whitehead1980]. However, it would be more efficient to directly fitting Cox models via penalized pseudo likelihood function. Last but not least, we plan to expand the proposed model to integrate external biology information. The main motivation for the integrative model is that biologically informed groupping of weak effects increases the power of detecting true associations between features and the outcome [@Peterson2016], and stabilizes the analysis results for reproducibility purpose. Such integration can be achieved by setting up a structural hyperprior on the inclusion indicator of the smoothing function null space $\bs \gamma^0$. The similar strategy has been used in Ferrari and Dunson [@Ferrari2020].






  <!-- Such prior set-ups ignore the null space of the smooth function, and entirely removes the variable out of the function. The "all-in-all-out" assumption makes differentiate linear and non-linear effect harder. In contrasts, our prior set up provides a more flexible solution, as the penalty for smoothness is locally adapative for the bases and hence retain the the null space if necessary.  -->

<!-- The "all-in-all-out" set-up was criticized for its inability to answering an important research question, if the effects are non-linear or not. On the other hand, the model can be much more flexible by allowing each dimension of the penalized space to have an independent indicator, i.e. $\gamma^{pen}_{jk}$ of $\beta^{pen}_{jk}$ for $k = 1\dots, K_j$. This prior set-up generalized to the group spike-and-slab. The additional flexibility doesn't not necessarily grand the model neither theoretical justification nor analytic simplicity. The spline penalty assumes a common smooth shrinkage $\lambda_j$ applied to all coefficients of the penalized space, which contradicts to the model setup. Besides, having multiple indicator variables complicates the decision of if non-linear effects are necessary. -->



